title: My GitHub Learning Lab Website
author: Mark Douglass
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is simply me following along to the GitHub Learning Lab course.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
